### ISSUE TITLE
How to work with this code?

### ISSUE THREAD

**Issue by samo313** [simongrest/chexpert-entries#2]
Could everyone please describe how should I start with this code?
I've started with Chexpert_predict and some error occurred of main()

>  in main   infile = sys.argv[1] 

> IndexError: list index out of range 

Any help would be really appreciated.

**Comment by simongrest** [comment]
This competition is run by the ML team at Stanford. In order to make a submission you need to use codalab. There's a tutorial on submission here: https://worksheets.codalab.org/worksheets/0x693b0063ee504702b21f94ffb2d99c6d/. 

The organisers require that your prediction program follow the following convention:
`#python src/<path-to-prediction-program> <input-data-csv-filename> <output-prediction-csv-path>`

`CheXpert_predict.py` is simply meant to do inference using pre-trained weights and to obey the call signature above. If you run it without command line arguments then the below lines that are intended to get the locations of the input and output files will fail:

`infile = sys.argv[1]`
`outfile = sys.argv[2]`

If you're just interested in how the model is trained have a look at the two python notebooks.
